// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package app

import (
	"hibot.us/chatbots-report/infraestructure/cache"
)

// Injectors from wire.go:

func CreateApp() *Application {
	cacheGateway := cache.NewRedisCacheGatewayImpl()
	application := NewApplication(cacheGateway)
	return application
}
