// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/LuisDiazM/firestore-reports/domain/usecases"
	"github.com/LuisDiazM/firestore-reports/infraestructure/cache"
	"github.com/LuisDiazM/firestore-reports/infraestructure/database"
)

// Injectors from wire.go:

func CreateApp() *Application {
	cacheGateway := cache.NewRedisCacheGatewayImpl()
	databaseGateway := database.NewDatabaseGatewayImp()
	reportsUsecase := usecases.NewReportUsecaseImp(cacheGateway, databaseGateway)
	application := NewApplication(cacheGateway, databaseGateway, reportsUsecase)
	return application
}
